### ISSUE TITLE
Kubernetes - Usage

### ISSUE THREAD

**Issue by manuparra** [manuparra/ska-serverless#5]
kubectl get pods -A -> Check all containers that are running

## Create a deployment file with this name and this content:

`deployment.yaml`

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carta-dev
spec:
  selector:
    matchLabels:
      run: carta-dev
  replicas: 2
  template:
    metadata:
      labels:
        run: carta-dev
    spec:
      containers:
      - name: carta-dev
        image: amigahub/carta-kubernetes:v1.0
        ports:
        - containerPort: 3002
```

Execute
`kubectl apply -f deployment.yaml`

Then create a file with the name: `service.yaml` and this content:

```
apiVersion: v1
kind: Service
metadata:
  name: carta-dev
  labels:
    run: carta-dev
spec:
  type: NodePort
  ports:
  - port: 3002
    targetPort: 3002
    nodePort: 30002
    protocol: TCP
  selector:
```

Execute
`kubectl apply -f service.yaml`

**Comment by manuparra** [comment]
If you want to update the number of replicas to 10 (for 10 uses ;) ) 👍🏼 
Update deployment.yaml with
👍🏼 
```
deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: carta-dev
spec:
  selector:
    matchLabels:
      run: carta-dev
  replicas: 10
  template:
    metadata:
      labels:
        run: carta-dev
    spec:
      containers:
      - name: carta-dev
        image: amigahub/carta-kubernetes:v1.0
        ports:
        - containerPort: 3002

```

`kubectl apply -f service.yaml`
